// Copyright IBM Corp. 2014, 2026
// Copyright 2026 Google LLC
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/iamconnectors/Connector.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/resource.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package iamconnectors

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"reflect"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/hashicorp/errwrap"
	"github.com/hashicorp/go-cty/cty"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/id"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/logging"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/structure"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"

	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/registry"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/transport"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/verify"

	"google.golang.org/api/googleapi"
)

var (
	_ = bytes.Clone
	_ = context.WithCancel
	_ = base64.NewDecoder
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = log.Print
	_ = http.Get
	_ = reflect.ValueOf
	_ = regexp.Match
	_ = slices.Min([]int{1})
	_ = sort.IntSlice{}
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = errwrap.Wrap
	_ = cty.BoolVal
	_ = diag.Diagnostic{}
	_ = customdiff.All
	_ = id.UniqueId
	_ = logging.LogLevel
	_ = retry.Retry
	_ = schema.Noop
	_ = validation.All
	_ = structure.ExpandJsonFromString
	_ = terraform.State{}
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = verify.ValidateEnum
	_ = googleapi.Error{}
)

func init() {
	registry.Schema{
		Name:        "google_iam_connectors_connector",
		ProductName: "iamconnectors",
		Type:        registry.SchemaTypeResource,
		Schema:      ResourceIamConnectorsConnector(),
	}.Register()
}

func ResourceIamConnectorsConnector() *schema.Resource {
	return &schema.Resource{
		Create: resourceIamConnectorsConnectorCreate,
		Read:   resourceIamConnectorsConnectorRead,
		Update: resourceIamConnectorsConnectorUpdate,
		Delete: resourceIamConnectorsConnectorDelete,

		Importer: &schema.ResourceImporter{
			State: resourceIamConnectorsConnectorImport,
		},

		Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(20 * time.Minute),
			Update: schema.DefaultTimeout(20 * time.Minute),
			Delete: schema.DefaultTimeout(20 * time.Minute),
		},

		CustomizeDiff: customdiff.All(
			tpgresource.ExclusiveStringValuesOnCreate("state", []string{"ENABLED"}),
			tpgresource.DefaultProviderProject,
		),

		Identity: &schema.ResourceIdentity{
			Version: 1,
			SchemaFunc: func() map[string]*schema.Schema {
				return map[string]*schema.Schema{
					"location": {
						Type:              schema.TypeString,
						RequiredForImport: true,
					},
					"connector_id": {
						Type:              schema.TypeString,
						RequiredForImport: true,
					},
					"project": {
						Type:              schema.TypeString,
						OptionalForImport: true,
					},
				}
			},
		},

		Schema: map[string]*schema.Schema{
			"connector_id": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: `The name of the connector.`,
			},
			"connector_type_params": {
				Type:        schema.TypeList,
				Required:    true,
				Description: `Connector type specific parameters.`,
				MaxItems:    1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"api_key": {
							Type:        schema.TypeList,
							Optional:    true,
							ForceNew:    true,
							Description: `ApiKey connector type parameters.`,
							MaxItems:    1,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"api_key": {
										Type:        schema.TypeString,
										Required:    true,
										Description: `The API key for this connector.`,
										Sensitive:   true,
									},
								},
							},
							ExactlyOneOf: []string{"connector_type_params.0.api_key", "connector_type_params.0.ge_connector_params", "connector_type_params.0.three_legged_oauth", "connector_type_params.0.two_legged_oauth"},
						},
						"ge_connector_params": {
							Type:        schema.TypeList,
							Optional:    true,
							ForceNew:    true,
							Description: `GeminiEnterprise connector type parameters.`,
							MaxItems:    1,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{},
							},
							ExactlyOneOf: []string{"connector_type_params.0.api_key", "connector_type_params.0.ge_connector_params", "connector_type_params.0.three_legged_oauth", "connector_type_params.0.two_legged_oauth"},
						},
						"three_legged_oauth": {
							Type:        schema.TypeList,
							Optional:    true,
							ForceNew:    true,
							Description: `ThreeLeggedOAuth connector type parameters.`,
							MaxItems:    1,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"authorization_url": {
										Type:        schema.TypeString,
										Required:    true,
										Description: `The authorization endpoint to send users to for consenting to delegate`,
									},
									"client_id": {
										Type:        schema.TypeString,
										Required:    true,
										Description: `The client ID of the OAuth client.`,
									},
									"client_secret": {
										Type:        schema.TypeString,
										Required:    true,
										Description: `The client secret of the OAuth client.`,
										Sensitive:   true,
									},
									"enable_pkce": {
										Type:        schema.TypeBool,
										Required:    true,
										Description: `Enables Proof Key for Code Exchange (PKCE) for the OAuth flow to prevent authorization code interception attacks.`,
									},
									"token_url": {
										Type:        schema.TypeString,
										Required:    true,
										Description: `The token endpoint for requesting tokens on behalf of an end user.`,
									},
									"redirect_url": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: `The redirect URL this connector uses for the OAuth exchange.`,
									},
								},
							},
							ExactlyOneOf: []string{"connector_type_params.0.api_key", "connector_type_params.0.ge_connector_params", "connector_type_params.0.three_legged_oauth", "connector_type_params.0.two_legged_oauth"},
						},
						"two_legged_oauth": {
							Type:        schema.TypeList,
							Optional:    true,
							ForceNew:    true,
							Description: `TwoLeggedOAuth connector type parameters.`,
							MaxItems:    1,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"client_id": {
										Type:        schema.TypeString,
										Required:    true,
										Description: `The client ID of the OAuth client.`,
									},
									"client_secret": {
										Type:        schema.TypeString,
										Required:    true,
										Description: `The client secret of the OAuth client.`,
										Sensitive:   true,
									},
									"token_endpoint": {
										Type:        schema.TypeString,
										Required:    true,
										Description: `The token endpoint of the OAuth client.`,
									},
								},
							},
							ExactlyOneOf: []string{"connector_type_params.0.api_key", "connector_type_params.0.ge_connector_params", "connector_type_params.0.three_legged_oauth", "connector_type_params.0.two_legged_oauth"},
						},
					},
				},
			},
			"location": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: `The location of the resource.`,
			},
			"allowed_scopes": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: `List of scopes that are allowed to be requested for this connector. If this list is non-empty, only scopes within this list may be requested. Scopes appearing in 'blocked_scopes' are disallowed even if they appear in 'allowed_scopes'.`,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
			"blocked_scopes": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: `List of scopes that are blocked from being requested for this connector. If a scope appears in this list, it may not be requested, even if it also appears in 'allowed_scopes'. 'blocked_scopes' takes precedence over 'allowed_scopes'.`,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
			"description": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: `The description of the resource.`,
			},
			"expire_time": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: `The time when the connector will expire.`,
			},
			"state": {
				Type:         schema.TypeString,
				Optional:     true,
				ValidateFunc: verify.ValidateEnum([]string{"ENABLED", "DISABLED", ""}),
				Description:  `The state of the connector. Default value: "ENABLED" Possible values: ["ENABLED", "DISABLED"]`,
				Default:      "ENABLED",
			},
			"workload_ids": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: `Workload identity (SPIFFE ID) of the agent.`,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
			"create_time": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: `The timestamp when the resource was created.`,
			},
			"deleted": {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: `This is set to true if the connector is deleted.`,
			},
			"update_time": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: `The timestamp when the resource was updated.`,
			},
			"project": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
				ForceNew: true,
			},
		},
		UseJSONNumber: true,
	}
}

func resourceIamConnectorsConnectorCreate(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	obj := make(map[string]interface{})
	descriptionProp, err := expandIamConnectorsConnectorDescription(d.Get("description"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("description"); !tpgresource.IsEmptyValue(reflect.ValueOf(descriptionProp)) && (ok || !reflect.DeepEqual(v, descriptionProp)) {
		obj["description"] = descriptionProp
	}
	allowedScopesProp, err := expandIamConnectorsConnectorAllowedScopes(d.Get("allowed_scopes"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("allowed_scopes"); !tpgresource.IsEmptyValue(reflect.ValueOf(allowedScopesProp)) && (ok || !reflect.DeepEqual(v, allowedScopesProp)) {
		obj["allowedScopes"] = allowedScopesProp
	}
	blockedScopesProp, err := expandIamConnectorsConnectorBlockedScopes(d.Get("blocked_scopes"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("blocked_scopes"); !tpgresource.IsEmptyValue(reflect.ValueOf(blockedScopesProp)) && (ok || !reflect.DeepEqual(v, blockedScopesProp)) {
		obj["blockedScopes"] = blockedScopesProp
	}
	connectorTypeParamsProp, err := expandIamConnectorsConnectorConnectorTypeParams(d.Get("connector_type_params"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("connector_type_params"); !tpgresource.IsEmptyValue(reflect.ValueOf(connectorTypeParamsProp)) && (ok || !reflect.DeepEqual(v, connectorTypeParamsProp)) {
		obj["connectorTypeParams"] = connectorTypeParamsProp
	}
	stateProp, err := expandIamConnectorsConnectorState(d.Get("state"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("state"); !tpgresource.IsEmptyValue(reflect.ValueOf(stateProp)) && (ok || !reflect.DeepEqual(v, stateProp)) {
		obj["state"] = stateProp
	}
	workloadIdsProp, err := expandIamConnectorsConnectorWorkloadIds(d.Get("workload_ids"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("workload_ids"); !tpgresource.IsEmptyValue(reflect.ValueOf(workloadIdsProp)) && (ok || !reflect.DeepEqual(v, workloadIdsProp)) {
		obj["workloadIds"] = workloadIdsProp
	}
	expireTimeProp, err := expandIamConnectorsConnectorExpireTime(d.Get("expire_time"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("expire_time"); !tpgresource.IsEmptyValue(reflect.ValueOf(expireTimeProp)) && (ok || !reflect.DeepEqual(v, expireTimeProp)) {
		obj["expireTime"] = expireTimeProp
	}

	url, err := tpgresource.ReplaceVars(d, config, "{{IamConnectorsBasePath}}projects/{{project}}/locations/{{location}}/connectors?connectorId={{connector_id}}")
	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Creating new Connector: %#v", obj)
	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for Connector: %s", err)
	}
	billingProject = project

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "POST",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Body:      obj,
		Timeout:   d.Timeout(schema.TimeoutCreate),
		Headers:   headers,
	})
	if err != nil {
		return fmt.Errorf("Error creating Connector: %s", err)
	}

	// Store the ID now
	id, err := tpgresource.ReplaceVars(d, config, "projects/{{project}}/locations/{{location}}/connectors/{{connector_id}}")
	if err != nil {
		return fmt.Errorf("Error constructing id: %s", err)
	}
	d.SetId(id)

	identity, err := d.Identity()
	if err == nil && identity != nil {
		if locationValue, ok := d.GetOk("location"); ok && locationValue.(string) != "" {
			if err = identity.Set("location", locationValue.(string)); err != nil {
				return fmt.Errorf("Error setting location: %s", err)
			}
		}
		if connectorIdValue, ok := d.GetOk("connector_id"); ok && connectorIdValue.(string) != "" {
			if err = identity.Set("connector_id", connectorIdValue.(string)); err != nil {
				return fmt.Errorf("Error setting connector_id: %s", err)
			}
		}
		if projectValue, ok := d.GetOk("project"); ok && projectValue.(string) != "" {
			if err = identity.Set("project", projectValue.(string)); err != nil {
				return fmt.Errorf("Error setting project: %s", err)
			}
		}
	} else {
		log.Printf("[DEBUG] (Create) identity not set: %s", err)
	}

	err = transport_tpg.PollingWaitTime(resourceIamConnectorsConnectorPollRead(d, meta), transport_tpg.PollCheckForExistence, "Creating Connector", d.Timeout(schema.TimeoutCreate), 5)
	if err != nil {
		return fmt.Errorf("Error waiting to create Connector: %s", err)
	}

	log.Printf("[DEBUG] Finished creating Connector %q: %#v", d.Id(), res)

	return resourceIamConnectorsConnectorRead(d, meta)
}

func resourceIamConnectorsConnectorPollRead(d *schema.ResourceData, meta interface{}) transport_tpg.PollReadFunc {
	return func() (map[string]interface{}, error) {
		config := meta.(*transport_tpg.Config)

		url, err := tpgresource.ReplaceVars(d, config, "{{IamConnectorsBasePath}}projects/{{project}}/locations/{{location}}/connectors/{{connector_id}}")

		if err != nil {
			return nil, err
		}

		billingProject := ""

		project, err := tpgresource.GetProject(d, config)
		if err != nil {
			return nil, fmt.Errorf("Error fetching project for Connector: %s", err)
		}
		billingProject = project

		// err == nil indicates that the billing_project value was found
		if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
			billingProject = bp
		}

		userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
		if err != nil {
			return nil, err
		}

		res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
			Config:    config,
			Method:    "GET",
			Project:   billingProject,
			RawURL:    url,
			UserAgent: userAgent,
		})
		if err != nil {
			return res, err
		}
		return res, nil
	}
}

func resourceIamConnectorsConnectorRead(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	url, err := tpgresource.ReplaceVars(d, config, "{{IamConnectorsBasePath}}projects/{{project}}/locations/{{location}}/connectors/{{connector_id}}")
	if err != nil {
		return err
	}

	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for Connector: %s", err)
	}
	billingProject = project

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "GET",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Headers:   headers,
	})
	if err != nil {
		return transport_tpg.HandleNotFoundError(err, d, fmt.Sprintf("IamConnectorsConnector %q", d.Id()))
	}

	log.Printf("[DEBUG] Finished reading IamConnectorsConnector %q: %#v", d.Id(), res)

	if err := d.Set("project", project); err != nil {
		return fmt.Errorf("Error reading Connector: %s", err)
	}

	if err := d.Set("description", flattenIamConnectorsConnectorDescription(res["description"], d, config)); err != nil {
		return fmt.Errorf("Error reading Connector: %s", err)
	}
	if err := d.Set("allowed_scopes", flattenIamConnectorsConnectorAllowedScopes(res["allowedScopes"], d, config)); err != nil {
		return fmt.Errorf("Error reading Connector: %s", err)
	}
	if err := d.Set("blocked_scopes", flattenIamConnectorsConnectorBlockedScopes(res["blockedScopes"], d, config)); err != nil {
		return fmt.Errorf("Error reading Connector: %s", err)
	}
	if err := d.Set("connector_type_params", flattenIamConnectorsConnectorConnectorTypeParams(res["connectorTypeParams"], d, config)); err != nil {
		return fmt.Errorf("Error reading Connector: %s", err)
	}
	if err := d.Set("state", flattenIamConnectorsConnectorState(res["state"], d, config)); err != nil {
		return fmt.Errorf("Error reading Connector: %s", err)
	}
	if err := d.Set("deleted", flattenIamConnectorsConnectorDeleted(res["deleted"], d, config)); err != nil {
		return fmt.Errorf("Error reading Connector: %s", err)
	}
	if err := d.Set("create_time", flattenIamConnectorsConnectorCreateTime(res["createTime"], d, config)); err != nil {
		return fmt.Errorf("Error reading Connector: %s", err)
	}
	if err := d.Set("update_time", flattenIamConnectorsConnectorUpdateTime(res["updateTime"], d, config)); err != nil {
		return fmt.Errorf("Error reading Connector: %s", err)
	}
	if err := d.Set("expire_time", flattenIamConnectorsConnectorExpireTime(res["expireTime"], d, config)); err != nil {
		return fmt.Errorf("Error reading Connector: %s", err)
	}

	identity, err := d.Identity()
	if err == nil && identity != nil {
		if v, ok := identity.GetOk("location"); !ok && v == "" {
			err = identity.Set("location", d.Get("location").(string))
			if err != nil {
				return fmt.Errorf("Error setting location: %s", err)
			}
		}
		if v, ok := identity.GetOk("connector_id"); !ok && v == "" {
			err = identity.Set("connector_id", d.Get("connector_id").(string))
			if err != nil {
				return fmt.Errorf("Error setting connector_id: %s", err)
			}
		}
		if v, ok := identity.GetOk("project"); !ok && v == "" {
			err = identity.Set("project", d.Get("project").(string))
			if err != nil {
				return fmt.Errorf("Error setting project: %s", err)
			}
		}
	} else {
		log.Printf("[DEBUG] (Read) identity not set: %s", err)
	}

	return nil
}

func resourceIamConnectorsConnectorUpdate(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}
	identity, err := d.Identity()
	if err == nil && identity != nil {
		if locationValue, ok := d.GetOk("location"); ok && locationValue.(string) != "" {
			if err = identity.Set("location", locationValue.(string)); err != nil {
				return fmt.Errorf("Error setting location: %s", err)
			}
		}
		if connectorIdValue, ok := d.GetOk("connector_id"); ok && connectorIdValue.(string) != "" {
			if err = identity.Set("connector_id", connectorIdValue.(string)); err != nil {
				return fmt.Errorf("Error setting connector_id: %s", err)
			}
		}
		if projectValue, ok := d.GetOk("project"); ok && projectValue.(string) != "" {
			if err = identity.Set("project", projectValue.(string)); err != nil {
				return fmt.Errorf("Error setting project: %s", err)
			}
		}
	} else {
		log.Printf("[DEBUG] (Update) identity not set: %s", err)
	}

	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for Connector: %s", err)
	}
	billingProject = project

	obj := make(map[string]interface{})
	descriptionProp, err := expandIamConnectorsConnectorDescription(d.Get("description"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("description"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, descriptionProp)) {
		obj["description"] = descriptionProp
	}
	allowedScopesProp, err := expandIamConnectorsConnectorAllowedScopes(d.Get("allowed_scopes"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("allowed_scopes"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, allowedScopesProp)) {
		obj["allowedScopes"] = allowedScopesProp
	}
	blockedScopesProp, err := expandIamConnectorsConnectorBlockedScopes(d.Get("blocked_scopes"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("blocked_scopes"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, blockedScopesProp)) {
		obj["blockedScopes"] = blockedScopesProp
	}
	connectorTypeParamsProp, err := expandIamConnectorsConnectorConnectorTypeParams(d.Get("connector_type_params"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("connector_type_params"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, connectorTypeParamsProp)) {
		obj["connectorTypeParams"] = connectorTypeParamsProp
	}
	stateProp, err := expandIamConnectorsConnectorState(d.Get("state"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("state"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, stateProp)) {
		obj["state"] = stateProp
	}
	workloadIdsProp, err := expandIamConnectorsConnectorWorkloadIds(d.Get("workload_ids"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("workload_ids"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, workloadIdsProp)) {
		obj["workloadIds"] = workloadIdsProp
	}
	expireTimeProp, err := expandIamConnectorsConnectorExpireTime(d.Get("expire_time"), d, config)
	if err != nil {
		return err
	} else if v, ok := d.GetOkExists("expire_time"); !tpgresource.IsEmptyValue(reflect.ValueOf(v)) && (ok || !reflect.DeepEqual(v, expireTimeProp)) {
		obj["expireTime"] = expireTimeProp
	}

	url, err := tpgresource.ReplaceVars(d, config, "{{IamConnectorsBasePath}}projects/{{project}}/locations/{{location}}/connectors/{{connector_id}}")
	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Updating Connector %q: %#v", d.Id(), obj)
	headers := make(http.Header)
	updateMask := []string{}

	if d.HasChange("description") {
		updateMask = append(updateMask, "description")
	}

	if d.HasChange("allowed_scopes") {
		updateMask = append(updateMask, "allowedScopes")
	}

	if d.HasChange("blocked_scopes") {
		updateMask = append(updateMask, "blockedScopes")
	}

	if d.HasChange("connector_type_params") {
		updateMask = append(updateMask, "connectorTypeParams")
	}

	if d.HasChange("state") {
		updateMask = append(updateMask, "state")
	}

	if d.HasChange("workload_ids") {
		updateMask = append(updateMask, "workloadIds")
	}

	if d.HasChange("expire_time") {
		updateMask = append(updateMask, "expireTime")
	}
	// updateMask is a URL parameter but not present in the schema, so ReplaceVars
	// won't set it
	url, err = transport_tpg.AddQueryParams(url, map[string]string{"updateMask": strings.Join(updateMask, ",")})
	if err != nil {
		return err
	}

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	// if updateMask is empty we are not updating anything so skip the post
	if len(updateMask) > 0 {
		res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
			Config:    config,
			Method:    "PATCH",
			Project:   billingProject,
			RawURL:    url,
			UserAgent: userAgent,
			Body:      obj,
			Timeout:   d.Timeout(schema.TimeoutUpdate),
			Headers:   headers,
		})

		if err != nil {
			return fmt.Errorf("Error updating Connector %q: %s", d.Id(), err)
		} else {
			log.Printf("[DEBUG] Finished updating Connector %q: %#v", d.Id(), res)
		}

	}

	return resourceIamConnectorsConnectorRead(d, meta)
}

func resourceIamConnectorsConnectorDelete(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*transport_tpg.Config)
	userAgent, err := tpgresource.GenerateUserAgentString(d, config.UserAgent)
	if err != nil {
		return err
	}

	billingProject := ""

	project, err := tpgresource.GetProject(d, config)
	if err != nil {
		return fmt.Errorf("Error fetching project for Connector: %s", err)
	}
	billingProject = project

	url, err := tpgresource.ReplaceVars(d, config, "{{IamConnectorsBasePath}}projects/{{project}}/locations/{{location}}/connectors/{{connector_id}}")
	if err != nil {
		return err
	}

	var obj map[string]interface{}

	// err == nil indicates that the billing_project value was found
	if bp, err := tpgresource.GetBillingProject(d, config); err == nil {
		billingProject = bp
	}

	headers := make(http.Header)

	log.Printf("[DEBUG] Deleting Connector %q", d.Id())
	res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    config,
		Method:    "DELETE",
		Project:   billingProject,
		RawURL:    url,
		UserAgent: userAgent,
		Body:      obj,
		Timeout:   d.Timeout(schema.TimeoutDelete),
		Headers:   headers,
	})
	if err != nil {
		return transport_tpg.HandleNotFoundError(err, d, "Connector")
	}

	log.Printf("[DEBUG] Finished deleting Connector %q: %#v", d.Id(), res)
	return nil
}

func resourceIamConnectorsConnectorImport(d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	config := meta.(*transport_tpg.Config)
	if err := tpgresource.ParseImportId([]string{
		"^projects/(?P<project>[^/]+)/locations/(?P<location>[^/]+)/connectors/(?P<connector_id>[^/]+)$",
		"^(?P<project>[^/]+)/(?P<location>[^/]+)/(?P<connector_id>[^/]+)$",
		"^(?P<location>[^/]+)/(?P<connector_id>[^/]+)$",
	}, d, config); err != nil {
		return nil, err
	}

	// Replace import id for the resource id
	id, err := tpgresource.ReplaceVars(d, config, "projects/{{project}}/locations/{{location}}/connectors/{{connector_id}}")
	if err != nil {
		return nil, fmt.Errorf("Error constructing id: %s", err)
	}
	d.SetId(id)

	return []*schema.ResourceData{d}, nil
}

func flattenIamConnectorsConnectorDescription(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenIamConnectorsConnectorAllowedScopes(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenIamConnectorsConnectorBlockedScopes(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenIamConnectorsConnectorConnectorTypeParams(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	if len(original) == 0 {
		return nil
	}
	transformed := make(map[string]interface{})
	transformed["three_legged_oauth"] =
		flattenIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauth(original["threeLeggedOauth"], d, config)
	transformed["two_legged_oauth"] =
		flattenIamConnectorsConnectorConnectorTypeParamsTwoLeggedOauth(original["twoLeggedOauth"], d, config)
	transformed["api_key"] =
		flattenIamConnectorsConnectorConnectorTypeParamsApiKey(original["apiKey"], d, config)
	transformed["ge_connector_params"] =
		flattenIamConnectorsConnectorConnectorTypeParamsGeConnectorParams(original["geConnectorParams"], d, config)
	return []interface{}{transformed}
}
func flattenIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauth(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	if len(original) == 0 {
		return nil
	}
	transformed := make(map[string]interface{})
	transformed["client_secret"] =
		flattenIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthClientSecret(original["clientSecret"], d, config)
	transformed["client_id"] =
		flattenIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthClientId(original["clientId"], d, config)
	transformed["redirect_url"] =
		flattenIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthRedirectUrl(original["redirectUrl"], d, config)
	transformed["authorization_url"] =
		flattenIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthAuthorizationUrl(original["authorizationUrl"], d, config)
	transformed["token_url"] =
		flattenIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthTokenUrl(original["tokenUrl"], d, config)
	transformed["enable_pkce"] =
		flattenIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthEnablePkce(original["enablePkce"], d, config)
	return []interface{}{transformed}
}
func flattenIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthClientSecret(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return d.Get("connector_type_params.0.three_legged_oauth.0.client_secret")
}

func flattenIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthClientId(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthRedirectUrl(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthAuthorizationUrl(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthTokenUrl(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthEnablePkce(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenIamConnectorsConnectorConnectorTypeParamsTwoLeggedOauth(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	if len(original) == 0 {
		return nil
	}
	transformed := make(map[string]interface{})
	transformed["client_secret"] =
		flattenIamConnectorsConnectorConnectorTypeParamsTwoLeggedOauthClientSecret(original["clientSecret"], d, config)
	transformed["client_id"] =
		flattenIamConnectorsConnectorConnectorTypeParamsTwoLeggedOauthClientId(original["clientId"], d, config)
	transformed["token_endpoint"] =
		flattenIamConnectorsConnectorConnectorTypeParamsTwoLeggedOauthTokenEndpoint(original["tokenEndpoint"], d, config)
	return []interface{}{transformed}
}
func flattenIamConnectorsConnectorConnectorTypeParamsTwoLeggedOauthClientSecret(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return d.Get("connector_type_params.0.two_legged_oauth.0.client_secret")
}

func flattenIamConnectorsConnectorConnectorTypeParamsTwoLeggedOauthClientId(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenIamConnectorsConnectorConnectorTypeParamsTwoLeggedOauthTokenEndpoint(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenIamConnectorsConnectorConnectorTypeParamsApiKey(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	original := v.(map[string]interface{})
	transformed := make(map[string]interface{})
	transformed["api_key"] =
		flattenIamConnectorsConnectorConnectorTypeParamsApiKeyApiKey(original["apiKey"], d, config)
	return []interface{}{transformed}
}
func flattenIamConnectorsConnectorConnectorTypeParamsApiKeyApiKey(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return d.Get("connector_type_params.0.api_key.0.api_key")
}

func flattenIamConnectorsConnectorConnectorTypeParamsGeConnectorParams(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	if v == nil {
		return nil
	}
	transformed := make(map[string]interface{})
	return []interface{}{transformed}
}

func flattenIamConnectorsConnectorState(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenIamConnectorsConnectorDeleted(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenIamConnectorsConnectorCreateTime(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenIamConnectorsConnectorUpdateTime(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func flattenIamConnectorsConnectorExpireTime(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
	return v
}

func expandIamConnectorsConnectorDescription(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandIamConnectorsConnectorAllowedScopes(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandIamConnectorsConnectorBlockedScopes(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandIamConnectorsConnectorConnectorTypeParams(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	if v == nil {
		return nil, nil
	}
	l := v.([]interface{})
	if len(l) == 0 || l[0] == nil {
		return nil, nil
	}
	raw := l[0]
	original := raw.(map[string]interface{})
	transformed := make(map[string]interface{})

	transformedThreeLeggedOauth, err := expandIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauth(original["three_legged_oauth"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedThreeLeggedOauth); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["threeLeggedOauth"] = transformedThreeLeggedOauth
	}

	transformedTwoLeggedOauth, err := expandIamConnectorsConnectorConnectorTypeParamsTwoLeggedOauth(original["two_legged_oauth"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedTwoLeggedOauth); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["twoLeggedOauth"] = transformedTwoLeggedOauth
	}

	transformedApiKey, err := expandIamConnectorsConnectorConnectorTypeParamsApiKey(original["api_key"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedApiKey); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["apiKey"] = transformedApiKey
	}

	transformedGeConnectorParams, err := expandIamConnectorsConnectorConnectorTypeParamsGeConnectorParams(original["ge_connector_params"], d, config)
	if err != nil {
		return nil, err
	} else {
		transformed["geConnectorParams"] = transformedGeConnectorParams
	}

	return transformed, nil
}

func expandIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauth(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	if v == nil {
		return nil, nil
	}
	l := v.([]interface{})
	if len(l) == 0 || l[0] == nil {
		return nil, nil
	}
	raw := l[0]
	original := raw.(map[string]interface{})
	transformed := make(map[string]interface{})

	transformedClientSecret, err := expandIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthClientSecret(original["client_secret"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedClientSecret); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["clientSecret"] = transformedClientSecret
	}

	transformedClientId, err := expandIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthClientId(original["client_id"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedClientId); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["clientId"] = transformedClientId
	}

	transformedRedirectUrl, err := expandIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthRedirectUrl(original["redirect_url"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedRedirectUrl); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["redirectUrl"] = transformedRedirectUrl
	}

	transformedAuthorizationUrl, err := expandIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthAuthorizationUrl(original["authorization_url"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedAuthorizationUrl); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["authorizationUrl"] = transformedAuthorizationUrl
	}

	transformedTokenUrl, err := expandIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthTokenUrl(original["token_url"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedTokenUrl); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["tokenUrl"] = transformedTokenUrl
	}

	transformedEnablePkce, err := expandIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthEnablePkce(original["enable_pkce"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedEnablePkce); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["enablePkce"] = transformedEnablePkce
	}

	return transformed, nil
}

func expandIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthClientSecret(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthClientId(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthRedirectUrl(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthAuthorizationUrl(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthTokenUrl(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandIamConnectorsConnectorConnectorTypeParamsThreeLeggedOauthEnablePkce(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandIamConnectorsConnectorConnectorTypeParamsTwoLeggedOauth(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	if v == nil {
		return nil, nil
	}
	l := v.([]interface{})
	if len(l) == 0 || l[0] == nil {
		return nil, nil
	}
	raw := l[0]
	original := raw.(map[string]interface{})
	transformed := make(map[string]interface{})

	transformedClientSecret, err := expandIamConnectorsConnectorConnectorTypeParamsTwoLeggedOauthClientSecret(original["client_secret"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedClientSecret); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["clientSecret"] = transformedClientSecret
	}

	transformedClientId, err := expandIamConnectorsConnectorConnectorTypeParamsTwoLeggedOauthClientId(original["client_id"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedClientId); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["clientId"] = transformedClientId
	}

	transformedTokenEndpoint, err := expandIamConnectorsConnectorConnectorTypeParamsTwoLeggedOauthTokenEndpoint(original["token_endpoint"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedTokenEndpoint); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["tokenEndpoint"] = transformedTokenEndpoint
	}

	return transformed, nil
}

func expandIamConnectorsConnectorConnectorTypeParamsTwoLeggedOauthClientSecret(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandIamConnectorsConnectorConnectorTypeParamsTwoLeggedOauthClientId(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandIamConnectorsConnectorConnectorTypeParamsTwoLeggedOauthTokenEndpoint(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandIamConnectorsConnectorConnectorTypeParamsApiKey(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	if v == nil {
		return nil, nil
	}
	l := v.([]interface{})
	if len(l) == 0 {
		return nil, nil
	}

	if l[0] == nil {
		transformed := make(map[string]interface{})
		return transformed, nil
	}
	raw := l[0]
	original := raw.(map[string]interface{})
	transformed := make(map[string]interface{})

	transformedApiKey, err := expandIamConnectorsConnectorConnectorTypeParamsApiKeyApiKey(original["api_key"], d, config)
	if err != nil {
		return nil, err
	} else if val := reflect.ValueOf(transformedApiKey); val.IsValid() && !tpgresource.IsEmptyValue(val) {
		transformed["apiKey"] = transformedApiKey
	}

	return transformed, nil
}

func expandIamConnectorsConnectorConnectorTypeParamsApiKeyApiKey(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandIamConnectorsConnectorConnectorTypeParamsGeConnectorParams(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	if v == nil {
		return nil, nil
	}
	l := v.([]interface{})
	if len(l) == 0 {
		return nil, nil
	}

	if l[0] == nil {
		transformed := make(map[string]interface{})
		return transformed, nil
	}
	transformed := make(map[string]interface{})

	return transformed, nil
}

func expandIamConnectorsConnectorState(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandIamConnectorsConnectorWorkloadIds(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}

func expandIamConnectorsConnectorExpireTime(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (interface{}, error) {
	return v, nil
}
