// Copyright IBM Corp. 2014, 2026
// Copyright 2026 Google LLC
// SPDX-License-Identifier: MPL-2.0
// ----------------------------------------------------------------------------
//
//	***     AUTO GENERATED CODE    ***    Type: Handwritten     ***
//
// ----------------------------------------------------------------------------
//
//	This code is generated by Magic Modules using the following:
//
//	Source file: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/services/iamconnectors/resource_iam_connectors_connector_test.go
//
//	DO NOT EDIT this file directly. Any changes made to this file will be
//	overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------
package iamconnectors_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/plancheck"

	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/acctest"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/envvar"
)

func TestAccIamConnectorsConnector_iamConnectorsConnectorUpdate(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)

	context := map[string]interface{}{
		"project":       envvar.GetTestProjectFromEnv(),
		"connector":     "connector" + randomSuffix,
		"random_suffix": randomSuffix,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckIamConnectorsConnectorDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccIamConnectorsConnector_iamConnectorsConnectorGeminiEnterpriseExample(context),
			},
			{
				ResourceName:            "google_iam_connectors_connector.default",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"connector_id", "connector_type_params.0.api_key.0.api_key", "connector_type_params.0.three_legged_oauth.0.client_secret", "connector_type_params.0.two_legged_oauth.0.client_secret", "location", "workload_ids"},
			},
			{
				Config: testAccIamConnectorsConnector_iamConnectorsConnectorUpdate(context),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(
							"google_iam_connectors_connector.default",
							plancheck.ResourceActionUpdate,
						),
					},
				},
			},
			{
				ResourceName:            "google_iam_connectors_connector.default",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"connector_id", "connector_type_params.0.api_key.0.api_key", "connector_type_params.0.three_legged_oauth.0.client_secret", "connector_type_params.0.two_legged_oauth.0.client_secret", "location", "workload_ids"},
			},
			{
				Config: testAccIamConnectorsConnector_iamConnectorsConnectorGeminiEnterpriseExample(context),
				ConfigPlanChecks: resource.ConfigPlanChecks{
					PreApply: []plancheck.PlanCheck{
						plancheck.ExpectResourceAction(
							"google_iam_connectors_connector.default",
							plancheck.ResourceActionUpdate,
						),
					},
				},
			},
			{
				ResourceName:            "google_iam_connectors_connector.default",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"connector_id", "connector_type_params.0.api_key.0.api_key", "connector_type_params.0.three_legged_oauth.0.client_secret", "connector_type_params.0.two_legged_oauth.0.client_secret", "location", "workload_ids"},
			},
		},
	})
}

func testAccIamConnectorsConnector_iamConnectorsConnectorUpdate(context map[string]interface{}) string {
	return acctest.Nprintf(`
provider "google-nightly" {}

resource "google_iam_connectors_connector" "default" {
  provider     = google-nightly

  location       = "us-east7"
  connector_id   = "%{connector}"

  connector_type_params {
    ge_connector_params {}
  }

  workload_ids = ["spiffe://example.com/spire/agent/k8s_psat/my-k8s-cluster/52174304-42f0-460b-9123-ed833d7904eb", "spiffe://example.com/spire/agent/k8s_psat/my-k8s-cluster/52174304-42f0-460b-9789-ed833d7904eb"]
}
`, context)
}
