// Copyright IBM Corp. 2014, 2026
// Copyright 2026 Google LLC
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package iamconnectors_test

import (
	"fmt"
	"log"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/acctest"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/envvar"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/transport"

	"google.golang.org/api/googleapi"
)

var (
	_ = fmt.Sprintf
	_ = log.Print
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = resource.TestMain
	_ = terraform.NewState
	_ = envvar.TestEnvVar
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = googleapi.Error{}
)

func TestAccIamConnectorsConnector_iamConnectorsConnectorBasicExample(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)

	context := map[string]interface{}{
		"connector":     "connector" + randomSuffix,
		"random_suffix": randomSuffix,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckIamConnectorsConnectorDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccIamConnectorsConnector_iamConnectorsConnectorBasicExample(context),
			},
			{
				ResourceName:            "google_iam_connectors_connector.default",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"connector_id", "connector_type_params.0.api_key.0.api_key", "connector_type_params.0.three_legged_oauth.0.client_secret", "connector_type_params.0.two_legged_oauth.0.client_secret", "location", "workload_ids"},
			},
			{
				ResourceName:       "google_iam_connectors_connector.default",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
		},
	})
}

func testAccIamConnectorsConnector_iamConnectorsConnectorBasicExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
provider "google-nightly" {}

resource "google_iam_connectors_connector" "default" {
  provider     = google-nightly

  location       = "us-east7"
  connector_id   = "%{connector}"

  connector_type_params {
    api_key {
      api_key = "foobar"
    }
  }
}
`, context)
}

func TestAccIamConnectorsConnector_iamConnectorsConnectorGeminiEnterpriseExample(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)

	context := map[string]interface{}{
		"connector":     "connector" + randomSuffix,
		"random_suffix": randomSuffix,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckIamConnectorsConnectorDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccIamConnectorsConnector_iamConnectorsConnectorGeminiEnterpriseExample(context),
			},
			{
				ResourceName:            "google_iam_connectors_connector.default",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"connector_id", "connector_type_params.0.api_key.0.api_key", "connector_type_params.0.three_legged_oauth.0.client_secret", "connector_type_params.0.two_legged_oauth.0.client_secret", "location", "workload_ids"},
			},
			{
				ResourceName:       "google_iam_connectors_connector.default",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
		},
	})
}

func testAccIamConnectorsConnector_iamConnectorsConnectorGeminiEnterpriseExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
provider "google-nightly" {}

resource "google_iam_connectors_connector" "default" {
  provider     = google-nightly

  location       = "us-east7"
  connector_id   = "%{connector}"

  connector_type_params {
    ge_connector_params {}
  }

  workload_ids = ["spiffe://example.com/spire/agent/k8s_psat/my-k8s-cluster/52174304-42f0-460b-9273-ed833d7904eb"]
}
`, context)
}

func TestAccIamConnectorsConnector_iamConnectorsConnectorThreeLeggedExample(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)

	context := map[string]interface{}{
		"connector":     "connector" + randomSuffix,
		"random_suffix": randomSuffix,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckIamConnectorsConnectorDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccIamConnectorsConnector_iamConnectorsConnectorThreeLeggedExample(context),
			},
			{
				ResourceName:            "google_iam_connectors_connector.default",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"connector_id", "connector_type_params.0.api_key.0.api_key", "connector_type_params.0.three_legged_oauth.0.client_secret", "connector_type_params.0.two_legged_oauth.0.client_secret", "location", "workload_ids"},
			},
			{
				ResourceName:       "google_iam_connectors_connector.default",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
		},
	})
}

func testAccIamConnectorsConnector_iamConnectorsConnectorThreeLeggedExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
provider "google-nightly" {}

resource "google_iam_connectors_connector" "default" {
  provider     = google-nightly

  location       = "us-east7"
  connector_id   = "%{connector}"

  allowed_scopes = ["https://www.googleapis.com/auth/cloud-platform", "https://www.googleapis.com/auth/userinfo.email"]

  connector_type_params {
    three_legged_oauth {
      client_id = "foo"
      client_secret = "bar"
      authorization_url = "baz"
      token_url = "qux"
      enable_pkce = true
    }
  }
}
`, context)
}

func TestAccIamConnectorsConnector_iamConnectorsConnectorTwoLeggedExample(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)

	context := map[string]interface{}{
		"connector":     "connector" + randomSuffix,
		"random_suffix": randomSuffix,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckIamConnectorsConnectorDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccIamConnectorsConnector_iamConnectorsConnectorTwoLeggedExample(context),
			},
			{
				ResourceName:            "google_iam_connectors_connector.default",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"connector_id", "connector_type_params.0.api_key.0.api_key", "connector_type_params.0.three_legged_oauth.0.client_secret", "connector_type_params.0.two_legged_oauth.0.client_secret", "location", "workload_ids"},
			},
			{
				ResourceName:       "google_iam_connectors_connector.default",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
		},
	})
}

func testAccIamConnectorsConnector_iamConnectorsConnectorTwoLeggedExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
provider "google-nightly" {}

resource "google_iam_connectors_connector" "default" {
  provider     = google-nightly

  location       = "us-east7"
  connector_id   = "%{connector}"

  allowed_scopes = ["https://www.googleapis.com/auth/cloud-platform"]
  blocked_scopes = ["https://www.googleapis.com/auth/userinfo.email"]

  connector_type_params {
    two_legged_oauth {
      client_id = "foo"
      client_secret = "bar"
      token_endpoint = "qux"
    }
  }
}
`, context)
}

func testAccCheckIamConnectorsConnectorDestroyProducer(t *testing.T) func(s *terraform.State) error {
	return func(s *terraform.State) error {
		for name, rs := range s.RootModule().Resources {
			if rs.Type != "google_iam_connectors_connector" {
				continue
			}
			if strings.HasPrefix(name, "data.") {
				continue
			}

			config := acctest.GoogleProviderConfig(t)

			url, err := tpgresource.ReplaceVarsForTest(config, rs, "{{IamConnectorsBasePath}}projects/{{project}}/locations/{{location}}/connectors/{{connector_id}}")
			if err != nil {
				return err
			}

			billingProject := ""

			if config.BillingProject != "" {
				billingProject = config.BillingProject
			}

			res, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
				Config:    config,
				Method:    "GET",
				Project:   billingProject,
				RawURL:    url,
				UserAgent: config.UserAgent,
			})

			if err != nil {
				return nil
			}

			if res["deleted"] == false {
				return fmt.Errorf("IamConnectorsConnector still exists at %s", url)
			}
		}

		return nil
	}
}
