// Copyright IBM Corp. 2014, 2026
// Copyright 2026 Google LLC
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

// Package networkservices contains resources, datasources, etc. for the network services service.
package networkservices

import (
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/registry"
)

const ProductName = "networkservices"

func init() {
	registry.Product{
		Name:    "networkservices",
		BaseUrl: "https://networkservices.googleapis.com/v1alpha1/",
	}.Register()
}
