// Copyright IBM Corp. 2014, 2026
// Copyright 2026 Google LLC
// SPDX-License-Identifier: MPL-2.0
// ----------------------------------------------------------------------------
//
//	***     AUTO GENERATED CODE    ***    Type: Handwritten     ***
//
// ----------------------------------------------------------------------------
//
//	This code is generated by Magic Modules using the following:
//
//	Source file: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/services/agentregistry/data_source_agent_registry_endpoint_test.go
//
//	DO NOT EDIT this file directly. Any changes made to this file will be
//	overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------
package agentregistry_test

import (
	"testing"

	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/acctest"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceAgentRegistryEndpoint_basic(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"endpoint_id": "add-here",
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceAgentRegistryEndpoint_basic(context),
			},
		},
	})
}

func testAccDataSourceAgentRegistryEndpoint_basic(context map[string]interface{}) string {
	return acctest.Nprintf(`
data "google_agent_registry_endpoint" "default" {
  location = "us-central1"
  endpoint_id = "%{endpoint_id}"
}
`, context)
}

func TestAccDataSourceAgentRegistryEndpoint_filter(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"filter": "displayName:Example API Endpoint",
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceAgentRegistryEndpoint_filter(context),
			},
		},
	})
}

func testAccDataSourceAgentRegistryEndpoint_filter(context map[string]interface{}) string {
	return acctest.Nprintf(`
data "google_agent_registry_endpoint" "default" {
  location = "us-central1"
  filter   = "%{filter}"
}
`, context)
}
