// Copyright IBM Corp. 2014, 2026
// Copyright 2026 Google LLC
// SPDX-License-Identifier: MPL-2.0
// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: Handwritten     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Source file: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/services/agentregistry/resource_agent_registry_service_test.go
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------
// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package agentregistry_test

import (
	"fmt"
	"log"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/acctest"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/envvar"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/transport"

	"google.golang.org/api/googleapi"
)

var (
	_ = fmt.Sprintf
	_ = log.Print
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = resource.TestMain
	_ = terraform.NewState
	_ = envvar.TestEnvVar
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = googleapi.Error{}
)

func TestAccAgentRegistryService_update(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix": acctest.RandString(t, 10),
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckAgentRegistryServiceDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccAgentRegistryService_update(context),
			},
			{
				ResourceName:            "google_agent_registry_service.default",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"location", "service_id"},
			},
			{
				Config: testAccAgentRegistryService_agentRegistryServiceBasicExample(context),
			},
			{
				ResourceName:            "google_agent_registry_service.default",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"location", "service_id"},
			},
			{
				Config: testAccAgentRegistryService_update(context),
			},
			{
				ResourceName:            "google_agent_registry_service.default",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"location", "service_id"},
			},
		},
	})
}

func testAccAgentRegistryService_update(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_agent_registry_service" "default" {
  location     = "us-central1"
  service_id   = "service%{random_suffix}"

  display_name = "My Updated Service"

  interfaces {
    url = "https://www.google.com/api"
    protocol_binding = "GRPC"
  }

  interfaces {
    url = "https://www.youtube.com/api"
    protocol_binding = "JSONRPC"
  }

  agent_spec {
    type    = "A2A_AGENT_CARD"
    content = jsonencode({
        name = {
          type        = "STRING"
          description = "A name"
      }})
  }
}
`, context)
}
