// Copyright IBM Corp. 2014, 2026
// Copyright 2026 Google LLC
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package agentregistry_test

import (
	"fmt"
	"log"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/acctest"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/envvar"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-nightly/google-nightly/transport"

	"google.golang.org/api/googleapi"
)

var (
	_ = fmt.Sprintf
	_ = log.Print
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = resource.TestMain
	_ = terraform.NewState
	_ = envvar.TestEnvVar
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = googleapi.Error{}
)

func TestAccAgentRegistryBinding_agentRegistryBindingBasicExample(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)

	context := map[string]interface{}{
		"binding":       "tf-test-ar-binding" + randomSuffix,
		"random_suffix": randomSuffix,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckAgentRegistryBindingDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccAgentRegistryBinding_agentRegistryBindingBasicExample(context),
			},
			{
				ResourceName:            "google_agent_registry_binding.default",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"binding_id", "location"},
			},
		},
	})
}

func testAccAgentRegistryBinding_agentRegistryBindingBasicExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_agent_registry_binding" "default" {
  provider = google-nightly

  location     = "us-central1"
  binding_id   = "%{binding}"
  display_name = "My Binding"

  source {
    identifier = data.google_agent_registry_agent.source.urn
  }

  target {
    identifier = data.google_agent_registry_mcp_server.target.urn
  }

  auth_provider_binding {
    auth_provider = google_iam_connectors_connector.default.id
  }
}

data "google_agent_registry_agent" "source" {
  provider = google-nightly

  location = "us-central1"
  filter   = "displayName:Source_Agent"
}

data "google_agent_registry_mcp_server" "target" {
  provider = google-nightly

  location = "us-central1"
  filter   = "displayName:Best_AI_Agent"
}

resource "google_iam_connectors_connector" "default" {
  provider     = google-nightly

  location       = "us-central1"
  connector_id   = "%{binding}"

  connector_type_params {
    ge_connector_params {}
  }
}
`, context)
}

func testAccCheckAgentRegistryBindingDestroyProducer(t *testing.T) func(s *terraform.State) error {
	return func(s *terraform.State) error {
		for name, rs := range s.RootModule().Resources {
			if rs.Type != "google_agent_registry_binding" {
				continue
			}
			if strings.HasPrefix(name, "data.") {
				continue
			}

			config := acctest.GoogleProviderConfig(t)

			url, err := tpgresource.ReplaceVarsForTest(config, rs, "{{AgentRegistryBasePath}}projects/{{project}}/locations/{{location}}/bindings/{{binding_id}}")
			if err != nil {
				return err
			}

			billingProject := ""

			if config.BillingProject != "" {
				billingProject = config.BillingProject
			}

			_, err = transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
				Config:    config,
				Method:    "GET",
				Project:   billingProject,
				RawURL:    url,
				UserAgent: config.UserAgent,
			})
			if err == nil {
				return fmt.Errorf("AgentRegistryBinding still exists at %s", url)
			}
		}

		return nil
	}
}
