// Copyright IBM Corp. 2014, 2026
// Copyright 2026 Google LLC
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/iap/AgentRegistryAgent.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples/base_configs/iam_test_file.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package iap_test

import (
	"fmt"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/acctest"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/envvar"
	"github.com/hashicorp/terraform-provider-google-nightly/google-nightly/tpgresource"
)

var (
	_ = fmt.Sprintf
	_ = strings.Trim
	_ = envvar.TestEnvVar
	_ = tpgresource.SetLabels
)

func TestAccIapAgentRegistryAgentIamBindingGenerated(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix":           acctest.RandString(t, 10),
		"role":                    "roles/iap.egressor",
		"condition_title":         "expires_after_2019_12_31",
		"condition_expr":          `request.time < timestamp(\"2020-01-01T00:00:00Z\")`,
		"condition_desc":          "Expiring at midnight of 2019-12-31",
		"condition_title_no_desc": "expires_after_2019_12_31-no-description",
		"condition_expr_no_desc":  `request.time < timestamp(\"2020-01-01T00:00:00Z\")`,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				Config: testAccIapAgentRegistryAgentIamBinding_basicGenerated(context),
			},
			{
				ResourceName:      "google_iap_agent_registry_agent_iam_binding.foo",
				ImportStateIdFunc: generateIapAgentRegistryAgentIAMBindingStateID("google_iap_agent_registry_agent_iam_binding.foo"),
				ImportState:       true,
				ImportStateVerify: true,
			},
			{
				// Test Iam Binding update
				Config: testAccIapAgentRegistryAgentIamBinding_updateGenerated(context),
			},
			{
				ResourceName:      "google_iap_agent_registry_agent_iam_binding.foo",
				ImportStateIdFunc: generateIapAgentRegistryAgentIAMBindingStateID("google_iap_agent_registry_agent_iam_binding.foo"),
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccIapAgentRegistryAgentIamMemberGenerated(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix":           acctest.RandString(t, 10),
		"role":                    "roles/iap.egressor",
		"condition_title":         "expires_after_2019_12_31",
		"condition_expr":          `request.time < timestamp(\"2020-01-01T00:00:00Z\")`,
		"condition_desc":          "Expiring at midnight of 2019-12-31",
		"condition_title_no_desc": "expires_after_2019_12_31-no-description",
		"condition_expr_no_desc":  `request.time < timestamp(\"2020-01-01T00:00:00Z\")`,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				// Test Iam Member creation (no update for member, no need to test)
				Config: testAccIapAgentRegistryAgentIamMember_basicGenerated(context),
			},
			{
				ResourceName:      "google_iap_agent_registry_agent_iam_member.foo",
				ImportStateIdFunc: generateIapAgentRegistryAgentIAMMemberStateID("google_iap_agent_registry_agent_iam_member.foo"),
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccIapAgentRegistryAgentIamPolicyGenerated(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix":           acctest.RandString(t, 10),
		"role":                    "roles/iap.egressor",
		"condition_title":         "expires_after_2019_12_31",
		"condition_expr":          `request.time < timestamp(\"2020-01-01T00:00:00Z\")`,
		"condition_desc":          "Expiring at midnight of 2019-12-31",
		"condition_title_no_desc": "expires_after_2019_12_31-no-description",
		"condition_expr_no_desc":  `request.time < timestamp(\"2020-01-01T00:00:00Z\")`,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				Config: testAccIapAgentRegistryAgentIamPolicy_basicGenerated(context),
				Check:  resource.TestCheckResourceAttrSet("data.google_iap_agent_registry_agent_iam_policy.foo", "policy_data"),
			},
			{
				ResourceName:      "google_iap_agent_registry_agent_iam_policy.foo",
				ImportStateIdFunc: generateIapAgentRegistryAgentIAMPolicyStateID("google_iap_agent_registry_agent_iam_policy.foo"),
				ImportState:       true,
				ImportStateVerify: true,
			},
			{
				Config: testAccIapAgentRegistryAgentIamPolicy_emptyBinding(context),
			},
			{
				ResourceName:      "google_iap_agent_registry_agent_iam_policy.foo",
				ImportStateIdFunc: generateIapAgentRegistryAgentIAMPolicyStateID("google_iap_agent_registry_agent_iam_policy.foo"),
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccIapAgentRegistryAgentIamBindingGenerated_withCondition(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix":           acctest.RandString(t, 10),
		"role":                    "roles/iap.egressor",
		"condition_title":         "expires_after_2019_12_31",
		"condition_expr":          `request.time < timestamp(\"2020-01-01T00:00:00Z\")`,
		"condition_desc":          "Expiring at midnight of 2019-12-31",
		"condition_title_no_desc": "expires_after_2019_12_31-no-description",
		"condition_expr_no_desc":  `request.time < timestamp(\"2020-01-01T00:00:00Z\")`,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				Config: testAccIapAgentRegistryAgentIamBinding_withConditionGenerated(context),
			},
			{
				ResourceName:      "google_iap_agent_registry_agent_iam_binding.foo",
				ImportStateIdFunc: generateIapAgentRegistryAgentIAMBindingStateID("google_iap_agent_registry_agent_iam_binding.foo"),
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccIapAgentRegistryAgentIamBindingGenerated_withAndWithoutCondition(t *testing.T) {
	// Multiple fine-grained resources
	acctest.SkipIfVcr(t)
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix":           acctest.RandString(t, 10),
		"role":                    "roles/iap.egressor",
		"condition_title":         "expires_after_2019_12_31",
		"condition_expr":          `request.time < timestamp(\"2020-01-01T00:00:00Z\")`,
		"condition_desc":          "Expiring at midnight of 2019-12-31",
		"condition_title_no_desc": "expires_after_2019_12_31-no-description",
		"condition_expr_no_desc":  `request.time < timestamp(\"2020-01-01T00:00:00Z\")`,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				Config: testAccIapAgentRegistryAgentIamBinding_withAndWithoutConditionGenerated(context),
			},
			{
				ResourceName:      "google_iap_agent_registry_agent_iam_binding.foo",
				ImportStateIdFunc: generateIapAgentRegistryAgentIAMBindingStateID("google_iap_agent_registry_agent_iam_binding.foo"),
				ImportState:       true,
				ImportStateVerify: true,
			},
			{
				ResourceName:      "google_iap_agent_registry_agent_iam_binding.foo2",
				ImportStateIdFunc: generateIapAgentRegistryAgentIAMBindingStateID("google_iap_agent_registry_agent_iam_binding.foo2"),
				ImportState:       true,
				ImportStateVerify: true,
			},
			{
				ResourceName:      "google_iap_agent_registry_agent_iam_binding.foo3",
				ImportStateIdFunc: generateIapAgentRegistryAgentIAMBindingStateID("google_iap_agent_registry_agent_iam_binding.foo3"),
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccIapAgentRegistryAgentIamMemberGenerated_withCondition(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix":           acctest.RandString(t, 10),
		"role":                    "roles/iap.egressor",
		"condition_title":         "expires_after_2019_12_31",
		"condition_expr":          `request.time < timestamp(\"2020-01-01T00:00:00Z\")`,
		"condition_desc":          "Expiring at midnight of 2019-12-31",
		"condition_title_no_desc": "expires_after_2019_12_31-no-description",
		"condition_expr_no_desc":  `request.time < timestamp(\"2020-01-01T00:00:00Z\")`,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				Config: testAccIapAgentRegistryAgentIamMember_withConditionGenerated(context),
			},
			{
				ResourceName:      "google_iap_agent_registry_agent_iam_member.foo",
				ImportStateIdFunc: generateIapAgentRegistryAgentIAMMemberStateID("google_iap_agent_registry_agent_iam_member.foo"),
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccIapAgentRegistryAgentIamMemberGenerated_withAndWithoutCondition(t *testing.T) {
	// Multiple fine-grained resources
	acctest.SkipIfVcr(t)
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix":           acctest.RandString(t, 10),
		"role":                    "roles/iap.egressor",
		"condition_title":         "expires_after_2019_12_31",
		"condition_expr":          `request.time < timestamp(\"2020-01-01T00:00:00Z\")`,
		"condition_desc":          "Expiring at midnight of 2019-12-31",
		"condition_title_no_desc": "expires_after_2019_12_31-no-description",
		"condition_expr_no_desc":  `request.time < timestamp(\"2020-01-01T00:00:00Z\")`,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				Config: testAccIapAgentRegistryAgentIamMember_withAndWithoutConditionGenerated(context),
			},
			{
				ResourceName:      "google_iap_agent_registry_agent_iam_member.foo",
				ImportStateIdFunc: generateIapAgentRegistryAgentIAMMemberStateID("google_iap_agent_registry_agent_iam_member.foo"),
				ImportState:       true,
				ImportStateVerify: true,
			},
			{
				ResourceName:      "google_iap_agent_registry_agent_iam_member.foo2",
				ImportStateIdFunc: generateIapAgentRegistryAgentIAMMemberStateID("google_iap_agent_registry_agent_iam_member.foo2"),
				ImportState:       true,
				ImportStateVerify: true,
			},
			{
				ResourceName:      "google_iap_agent_registry_agent_iam_member.foo3",
				ImportStateIdFunc: generateIapAgentRegistryAgentIAMMemberStateID("google_iap_agent_registry_agent_iam_member.foo3"),
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccIapAgentRegistryAgentIamPolicyGenerated_withCondition(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix":           acctest.RandString(t, 10),
		"role":                    "roles/iap.egressor",
		"condition_title":         "expires_after_2019_12_31",
		"condition_expr":          `request.time < timestamp(\"2020-01-01T00:00:00Z\")`,
		"condition_desc":          "Expiring at midnight of 2019-12-31",
		"condition_title_no_desc": "expires_after_2019_12_31-no-description",
		"condition_expr_no_desc":  `request.time < timestamp(\"2020-01-01T00:00:00Z\")`,
	}

	// Test should have 2 bindings: one with a description and one without. Any < chars are converted to a unicode character by the API.
	expectedPolicyData := acctest.Nprintf(`{"bindings":[{"condition":{"description":"%{condition_desc}","expression":"%{condition_expr}","title":"%{condition_title}"},"members":["user:admin@hashicorptest.com"],"role":"%{role}"},{"condition":{"expression":"%{condition_expr}","title":"%{condition_title}-no-description"},"members":["user:admin@hashicorptest.com"],"role":"%{role}"}]}`, context)
	expectedPolicyData = strings.Replace(expectedPolicyData, "<", "\\u003c", -1)

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				Config: testAccIapAgentRegistryAgentIamPolicy_withConditionGenerated(context),
				Check: resource.ComposeAggregateTestCheckFunc(
					// TODO - uncomment once https://github.com/GoogleCloudPlatform/magic-modules/pull/6466 merged
					// resource.TestCheckResourceAttr("data.google_iam_policy.foo", "policy_data", expectedPolicyData),
					resource.TestCheckResourceAttr("google_iap_agent_registry_agent_iam_policy.foo", "policy_data", expectedPolicyData),
					resource.TestCheckResourceAttrWith("data.google_iam_policy.foo", "policy_data", tpgresource.CheckGoogleIamPolicy),
				),
			},
			{
				ResourceName:      "google_iap_agent_registry_agent_iam_policy.foo",
				ImportStateIdFunc: generateIapAgentRegistryAgentIAMPolicyStateID("google_iap_agent_registry_agent_iam_policy.foo"),
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccIapAgentRegistryAgentIamMember_basicGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
data "google_agent_registry_agent" "default" {
  location = "us-central1"
  filter = "displayName:Workspace Agent"
}

resource "google_iap_agent_registry_agent_iam_member" "foo" {
  project = data.google_agent_registry_agent.default.project
  location = data.google_agent_registry_agent.default.location
  agent_id = data.google_agent_registry_agent.default.agent_id
  role = "%{role}"
  member = "user:admin@hashicorptest.com"
}
`, context)
}

func testAccIapAgentRegistryAgentIamPolicy_basicGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
data "google_agent_registry_agent" "default" {
  location = "us-central1"
  filter = "displayName:Workspace Agent"
}

data "google_iam_policy" "foo" {
  binding {
    role = "%{role}"
    members = ["user:admin@hashicorptest.com"]
  }
}

resource "google_iap_agent_registry_agent_iam_policy" "foo" {
  project = data.google_agent_registry_agent.default.project
  location = data.google_agent_registry_agent.default.location
  agent_id = data.google_agent_registry_agent.default.agent_id
  policy_data = data.google_iam_policy.foo.policy_data
}

data "google_iap_agent_registry_agent_iam_policy" "foo" {
  project = data.google_agent_registry_agent.default.project
  location = data.google_agent_registry_agent.default.location
  agent_id = data.google_agent_registry_agent.default.agent_id
  depends_on = [
    google_iap_agent_registry_agent_iam_policy.foo
  ]
}
`, context)
}

func testAccIapAgentRegistryAgentIamPolicy_emptyBinding(context map[string]interface{}) string {
	return acctest.Nprintf(`
data "google_agent_registry_agent" "default" {
  location = "us-central1"
  filter = "displayName:Workspace Agent"
}

data "google_iam_policy" "foo" {
}

resource "google_iap_agent_registry_agent_iam_policy" "foo" {
  project = data.google_agent_registry_agent.default.project
  location = data.google_agent_registry_agent.default.location
  agent_id = data.google_agent_registry_agent.default.agent_id
  policy_data = data.google_iam_policy.foo.policy_data
}
`, context)
}

func testAccIapAgentRegistryAgentIamBinding_basicGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
data "google_agent_registry_agent" "default" {
  location = "us-central1"
  filter = "displayName:Workspace Agent"
}

resource "google_iap_agent_registry_agent_iam_binding" "foo" {
  project = data.google_agent_registry_agent.default.project
  location = data.google_agent_registry_agent.default.location
  agent_id = data.google_agent_registry_agent.default.agent_id
  role = "%{role}"
  members = ["user:admin@hashicorptest.com"]
}
`, context)
}

func testAccIapAgentRegistryAgentIamBinding_updateGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
data "google_agent_registry_agent" "default" {
  location = "us-central1"
  filter = "displayName:Workspace Agent"
}

resource "google_iap_agent_registry_agent_iam_binding" "foo" {
  project = data.google_agent_registry_agent.default.project
  location = data.google_agent_registry_agent.default.location
  agent_id = data.google_agent_registry_agent.default.agent_id
  role = "%{role}"
  members = ["user:admin@hashicorptest.com", "user:gterraformtest1@gmail.com"]
}
`, context)
}

func testAccIapAgentRegistryAgentIamBinding_withConditionGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
data "google_agent_registry_agent" "default" {
  location = "us-central1"
  filter = "displayName:Workspace Agent"
}

resource "google_iap_agent_registry_agent_iam_binding" "foo" {
  project = data.google_agent_registry_agent.default.project
  location = data.google_agent_registry_agent.default.location
  agent_id = data.google_agent_registry_agent.default.agent_id
  role = "%{role}"
  members = ["user:admin@hashicorptest.com"]
  condition {
    title       = "%{condition_title}"
    description = "%{condition_desc}"
    expression  = "%{condition_expr}"
  }
}
`, context)
}

func testAccIapAgentRegistryAgentIamBinding_withAndWithoutConditionGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
data "google_agent_registry_agent" "default" {
  location = "us-central1"
  filter = "displayName:Workspace Agent"
}

resource "google_iap_agent_registry_agent_iam_binding" "foo" {
  project = data.google_agent_registry_agent.default.project
  location = data.google_agent_registry_agent.default.location
  agent_id = data.google_agent_registry_agent.default.agent_id
  role = "%{role}"
  members = ["user:admin@hashicorptest.com"]
}

resource "google_iap_agent_registry_agent_iam_binding" "foo2" {
  project = data.google_agent_registry_agent.default.project
  location = data.google_agent_registry_agent.default.location
  agent_id = data.google_agent_registry_agent.default.agent_id
  role = "%{role}"
  members = ["user:admin@hashicorptest.com"]
  condition {
    title       = "%{condition_title}"
    description = "%{condition_desc}"
    expression  = "%{condition_expr}"
  }
}

resource "google_iap_agent_registry_agent_iam_binding" "foo3" {
  project = data.google_agent_registry_agent.default.project
  location = data.google_agent_registry_agent.default.location
  agent_id = data.google_agent_registry_agent.default.agent_id
  role = "%{role}"
  members = ["user:admin@hashicorptest.com"]
  condition {
    # Check that lack of description doesn't cause any issues
    # Relates to issue : https://github.com/hashicorp/terraform-provider-google/issues/8701
    title       = "%{condition_title_no_desc}"
    expression  = "%{condition_expr_no_desc}"
  }
}
`, context)
}

func testAccIapAgentRegistryAgentIamMember_withConditionGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
data "google_agent_registry_agent" "default" {
  location = "us-central1"
  filter = "displayName:Workspace Agent"
}

resource "google_iap_agent_registry_agent_iam_member" "foo" {
  project = data.google_agent_registry_agent.default.project
  location = data.google_agent_registry_agent.default.location
  agent_id = data.google_agent_registry_agent.default.agent_id
  role = "%{role}"
  member = "user:admin@hashicorptest.com"
  condition {
    title       = "%{condition_title}"
    description = "%{condition_desc}"
    expression  = "%{condition_expr}"
  }
}
`, context)
}

func testAccIapAgentRegistryAgentIamMember_withAndWithoutConditionGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
data "google_agent_registry_agent" "default" {
  location = "us-central1"
  filter = "displayName:Workspace Agent"
}

resource "google_iap_agent_registry_agent_iam_member" "foo" {
  project = data.google_agent_registry_agent.default.project
  location = data.google_agent_registry_agent.default.location
  agent_id = data.google_agent_registry_agent.default.agent_id
  role = "%{role}"
  member = "user:admin@hashicorptest.com"
}

resource "google_iap_agent_registry_agent_iam_member" "foo2" {
  project = data.google_agent_registry_agent.default.project
  location = data.google_agent_registry_agent.default.location
  agent_id = data.google_agent_registry_agent.default.agent_id
  role = "%{role}"
  member = "user:admin@hashicorptest.com"
  condition {
    title       = "%{condition_title}"
    description = "%{condition_desc}"
    expression  = "%{condition_expr}"
  }
}

resource "google_iap_agent_registry_agent_iam_member" "foo3" {
  project = data.google_agent_registry_agent.default.project
  location = data.google_agent_registry_agent.default.location
  agent_id = data.google_agent_registry_agent.default.agent_id
  role = "%{role}"
  member = "user:admin@hashicorptest.com"
  condition {
    # Check that lack of description doesn't cause any issues
    # Relates to issue : https://github.com/hashicorp/terraform-provider-google/issues/8701
    title       = "%{condition_title_no_desc}"
    expression  = "%{condition_expr_no_desc}"
  }
}
`, context)
}

func testAccIapAgentRegistryAgentIamPolicy_withConditionGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
data "google_agent_registry_agent" "default" {
  location = "us-central1"
  filter = "displayName:Workspace Agent"
}

data "google_iam_policy" "foo" {
  binding {
    role = "%{role}"
    members = ["user:admin@hashicorptest.com"]
    condition {
      # Check that lack of description doesn't cause any issues
      # Relates to issue : https://github.com/hashicorp/terraform-provider-google/issues/8701
      title       = "%{condition_title_no_desc}"
      expression  = "%{condition_expr_no_desc}"
    }
  }
  binding {
    role = "%{role}"
    members = ["user:admin@hashicorptest.com"]
    condition {
      title       = "%{condition_title}"
      description = "%{condition_desc}"
      expression  = "%{condition_expr}"
    }
  }
}

resource "google_iap_agent_registry_agent_iam_policy" "foo" {
  project = data.google_agent_registry_agent.default.project
  location = data.google_agent_registry_agent.default.location
  agent_id = data.google_agent_registry_agent.default.agent_id
  policy_data = data.google_iam_policy.foo.policy_data
}
`, context)
}
func generateIapAgentRegistryAgentIAMPolicyStateID(iamResourceAddr string) func(*terraform.State) (string, error) {
	return func(state *terraform.State) (string, error) {
		var rawState map[string]string
		for _, m := range state.Modules {
			if len(m.Resources) > 0 {
				if v, ok := m.Resources[iamResourceAddr]; ok {
					rawState = v.Primary.Attributes
				}
			}
		}
		fmt.Printf("raw state %s\n", rawState)
		project := tpgresource.GetResourceNameFromSelfLink(rawState["project"])
		location := tpgresource.GetResourceNameFromSelfLink(rawState["location"])
		agent_id := tpgresource.GetResourceNameFromSelfLink(rawState["agent_id"])
		return acctest.BuildIAMImportId(fmt.Sprintf("projects/%s/locations/%s/iap_web/agentRegistry/agents/%s", project, location, agent_id), "", "", rawState["condition.0.title"]), nil
	}
}

func generateIapAgentRegistryAgentIAMBindingStateID(iamResourceAddr string) func(*terraform.State) (string, error) {
	return func(state *terraform.State) (string, error) {
		var rawState map[string]string
		for _, m := range state.Modules {
			if len(m.Resources) > 0 {
				if v, ok := m.Resources[iamResourceAddr]; ok {
					rawState = v.Primary.Attributes
				}
			}
		}
		fmt.Printf("raw state %s\n", rawState)
		project := tpgresource.GetResourceNameFromSelfLink(rawState["project"])
		location := tpgresource.GetResourceNameFromSelfLink(rawState["location"])
		agent_id := tpgresource.GetResourceNameFromSelfLink(rawState["agent_id"])
		return acctest.BuildIAMImportId(fmt.Sprintf("projects/%s/locations/%s/iap_web/agentRegistry/agents/%s", project, location, agent_id), rawState["role"], "", rawState["condition.0.title"]), nil
	}
}

func generateIapAgentRegistryAgentIAMMemberStateID(iamResourceAddr string) func(*terraform.State) (string, error) {
	return func(state *terraform.State) (string, error) {
		var rawState map[string]string
		for _, m := range state.Modules {
			if len(m.Resources) > 0 {
				if v, ok := m.Resources[iamResourceAddr]; ok {
					rawState = v.Primary.Attributes
				}
			}
		}
		fmt.Printf("raw state %s\n", rawState)
		project := tpgresource.GetResourceNameFromSelfLink(rawState["project"])
		location := tpgresource.GetResourceNameFromSelfLink(rawState["location"])
		agent_id := tpgresource.GetResourceNameFromSelfLink(rawState["agent_id"])
		return acctest.BuildIAMImportId(fmt.Sprintf("projects/%s/locations/%s/iap_web/agentRegistry/agents/%s", project, location, agent_id), rawState["role"], rawState["member"], rawState["condition.0.title"]), nil
	}
}
